config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  get '/shops', to: 'homes#index'
  get '/shops/new', to: 'homes#authorized'
  get '/shops/:id', to: 'homes#index'
  get '/shops/:id/reviews', to: 'homes#index'

  namespace :api do
    namespace :v1 do
      resources :shops, only: [:index, :show, :create] do
        resources :reviews, only: [:create]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :body, presence: true

  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews

  mount_uploader :profile_photo, ProfilePhotoUploader

  def admin?
    role == "admin"
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController

  def create
    review = Review.new(review_params)
    review.shop =  Shop.find(params[:shop_id])
    review.user = current_user

    if review.save
      render json: review, serializer: ReviewSerializer
    else
      render json: { error: review.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/api/v1/shops_controller.rb
class Api::V1::ShopsController < ApiController
  before_action :authorize_admin, only: [:create]

  def index
    render json: Shop.order(name: :asc)
  end

  def show
    render json: Shop.find(params[:id]), serializer: ShopShowSerializer, include: ['reviews.user']
  end

  def create
    shop = Shop.new(shop_params)

    if shop.picture == ""
      shop.picture = "https://i.pinimg.com/originals/c4/af/a0/c4afa0ab58a1343be2b944ec28a5fdae.jpg"
    end

    if shop.save
      render json: { shop: shop }
    else
      render json: { error: shop.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :address, :city, :state, :zip, :website, :telephone, :picture)
  end

  def authorize_admin
    if !user_signed_in? && !(current_user.role == "admin")
      render json: {error: ["Only admins have access to this page."]}
    end
  end

  def authenticate_user
    if !user_signed_in?
      render json: {error: ["You need to be signed in first."]}
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_photo])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authorize_admin, only: [:authorized]

  def index
  end

  def authorized
  end

  protected 

  def authorize_admin
    if !current_user
      redirect_to new_user_session_path
      flash[:alert] = "You need to be signed in first."
    elsif current_user.role != "admin"
      flash[:error] = "Only admins have access to this page."
      redirect_to shops_path
    end
  end
end

app/views/homes/authenticated.html.erb
<div id="app">

</div>

app/views/homes/authorized.html.erb
<div id="app">

</div>

app/views/homes/index.html.erb
<div id="app">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bubble Tea Devotees</title>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script src="https://kit.fontawesome.com/9191ab314f.js" crossorigin="anonymous"></script>
</head>
<body>

  <nav class="top-bar">
    <h1 class="header-text">
      <%= image_tag("android-chrome-192x192.png", :class => "bubble-tea-icon", :alt => "bubble tea") %>
      <a class="header-link" href="/">Bubble Tea Devotees</a>
    </h1>

    <section class="top-bar-section">
      <%- if current_user -%>
        <%- if current_user.role == "admin" -%>
          <button type="button" class="button">
            <%= link_to 'Add New Shop', shops_new_path %></li>
          </button>
        <%- end -%>
        <button type="button" class="button">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        </button>
      <%- else -%>
        <button type="button" class="button">
          <%= link_to 'Sign Up', new_user_registration_path %></li>
        </button>
        <button type="button" class="button">
          <%= link_to 'Sign In', new_user_session_path %></li>
        </button>
      <%- end -%>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>

<footer>
  <div class="up-arrow cell">
    <a href="#top"><i class="fa fa-chevron-circle-up" aria-hidden="true"></i></a>
  </div>
  <div class="row author-info">
    <div class="columns">
      <h4>Meet the Devo-Teas</h4>
      <ul class="menu simple tag-section">
        <li><a class="footer-link" target="_blank" href="https://github.com/OoL33/bubble-tea-shop-reviews">GitHub</a></li>
        <li><a class="footer-link" target="_blank" href="https://www.linkedin.com/in/alanaolee/">Alana Lee</a></li>
        <li><a class="footer-link" target="_blank" href="https://www.linkedin.com/in/kathleencfoley/">Kathleen Foley</a></li>
        <li><a class="footer-link" target="_blank" href="https://www.linkedin.com/in/kwong402/">Karen Wong</a></li>
        <li><a class="footer-link" target="_blank" href="https://www.linkedin.com/in/taylorkingstonle/">Taylor Le</a></li>
      </ul>
    </div>
  </div>
</footer>
</html>